### ISSUE TITLE
logged out after refresh page when change App_URL

### ISSUE THREAD

**Issue by shinnlu** [skn-036/cms-role-permission-laravel-vue-spa#23]
Hi,
i found it's not possible to change APP_URL, after change it will Redirected to login after refreshing any protected page.

# php artisan serve with original .env
- clone the source and make it running
- login and refresh without problem
```
npm run dev
php artisan serve
```

# apache server & change .env
- change APP_URL to https://cmsvue.test/
- change SANCTUM_STATEFUL_DOMAINS=https://cmsvue.test/
`npm run dev`
after login successful, any refresh will redirect to login page.

**Comment by skn-036** [comment]
Hi shinnlu
I have made a minor change. Please check after pulling. If the error persists, I need more information about the error. Like any error on the console or any error on the network request to debug the issue properly.

Thanks

**Comment by shinnlu** [comment]
i may found the problem.
i need to run `php artisan optimize:clear` to clear the session cache after change APP_URL and SANCTUM_STATEFUL_DOMAINS, or the session will keep logged out when refresh.

thank you for your project, it is a good start to learn role based project with vue.

**Comment by skn-036** [comment]
Hi Thanks. I have tried to made it in such a way, it will easily scale up to any project. Hope it helps !!!
