### ISSUE TITLE
 failed to login

### ISSUE THREAD

**Issue by abelnexus** [skn-036/cms-role-permission-laravel-vue-spa#3]
![Captura](https://user-images.githubusercontent.com/34687414/137210720-41feba30-42ad-4261-a36e-373b360a392c.PNG)

**Comment by besmiralia** [comment]
@abelnexus Were you able to fix this?

**Comment by skn-036** [comment]
Hi, I think this error occurred because Laravel sanctum doesn't configured properly. I have updated the .env.example.
